cmake_minimum_required(VERSION 3.22)
project(prova_pthreads LANGUAGES C)
if(NOT WIN32 OR NOT EXISTS "${SDK_PTHREADS}/pthread.c")
  message(FATAL_ERROR "Windows e fonte pthreads explícito necessários")
endif()
add_library(w32-pthreads SHARED "${SDK_PTHREADS}/pthread.c" marca.c)
target_compile_definitions(w32-pthreads PRIVATE __CLEANUP_C PTW32_BUILD)
target_include_directories(w32-pthreads PRIVATE "${SDK_PTHREADS}")
set_target_properties(w32-pthreads PROPERTIES OUTPUT_NAME w32-pthreads)
