# SPDX-License-Identifier: GPL-3.0-or-later
# Usado na configuração e a cada build, sem depender de uma recompilação do plugin.
if(NOT DEFINED QUALL_LICENCA_PLUGIN)
  set(QUALL_LICENCA_PLUGIN "${CMAKE_CURRENT_LIST_DIR}/../LICENSE")
endif()
if(NOT DEFINED QUALL_ESCOPO_PLUGIN)
  set(QUALL_ESCOPO_PLUGIN "${CMAKE_CURRENT_LIST_DIR}/../LICENSE-SCOPE.md")
endif()
if(NOT DEFINED QUALL_LICENCA_NUCLEO)
  set(QUALL_LICENCA_NUCLEO "${CMAKE_CURRENT_LIST_DIR}/../../../LICENSE")
endif()
foreach(documento IN ITEMS QUALL_AVISOS QUALL_LICENCA_PLUGIN QUALL_ESCOPO_PLUGIN QUALL_LICENCA_NUCLEO)
  if(NOT DEFINED ${documento} OR NOT EXISTS "${${documento}}" OR IS_DIRECTORY "${${documento}}")
    message(FATAL_ERROR "Documento de licença/avisos ausente (${documento}): ${${documento}}")
  endif()
  file(SIZE "${${documento}}" tamanho_do_documento)
  if(tamanho_do_documento EQUAL 0)
    message(FATAL_ERROR "Documento de licença/avisos vazio (${documento}): ${${documento}}")
  endif()
endforeach()
if(DEFINED QUALL_DESTINO_AVISOS)
  get_filename_component(pasta_dos_avisos "${QUALL_DESTINO_AVISOS}" DIRECTORY)
  if(DEFINED QUALL_DADOS_ORIGEM)
    # A pasta é staging da build: não preservar idiomas/arquivos removidos das fontes.
    file(REMOVE_RECURSE "${pasta_dos_avisos}")
    file(COPY "${QUALL_DADOS_ORIGEM}/" DESTINATION "${pasta_dos_avisos}")
  endif()
  file(MAKE_DIRECTORY "${pasta_dos_avisos}")
  file(COPY_FILE "${QUALL_AVISOS}" "${QUALL_DESTINO_AVISOS}" ONLY_IF_DIFFERENT)
  file(COPY_FILE "${QUALL_LICENCA_PLUGIN}" "${pasta_dos_avisos}/LICENSE" ONLY_IF_DIFFERENT)
  file(COPY_FILE "${QUALL_ESCOPO_PLUGIN}" "${pasta_dos_avisos}/LICENSE-SCOPE.md" ONLY_IF_DIFFERENT)
  file(COPY_FILE "${QUALL_LICENCA_NUCLEO}" "${pasta_dos_avisos}/LICENSE-MPL-2.0.txt" ONLY_IF_DIFFERENT)
endif()
