#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Generate neutral example assets from original geometry, using Python's stdlib.

Run from any directory: python3 tools/icones/gerar.py
These assets are placeholders for source builds, not the product's release artwork.
No font, image, upstream icon path or user media is read by this generator.
"""

import binascii
import json
import math
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ANDROID = ROOT / "apps/android/app/src/main/res"
WINDOWS_SIZES = (16, 20, 24, 32, 40, 48, 64, 96, 128, 256)
XML_HEAD = '<?xml version="1.0" encoding="utf-8"?>\n'
XML_NOTICE = '<!-- SPDX-License-Identifier: MPL-2.0; original example geometry, generated by tools/icones/gerar.py. -->\n'
ANDROID_NS = 'xmlns:android="http://schemas.android.com/apk/res/android"'
OUTPUTS = []


def write(relative, data):
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data.encode("utf-8") if isinstance(data, str) else data)
    OUTPUTS.append(relative)


def chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", binascii.crc32(kind + data) & 0xffffffff)


def rgba(side, transparent=False):
    """A four-cell grid, with integer coordinates and no copied brand geometry."""
    pixels = bytearray()
    for y in range(side):
        pixels.append(0)  # PNG filter: none
        for x in range(side):
            u, v = (x + 0.5) / side, (y + 0.5) / side
            outside = transparent and not (0.08 <= u <= 0.92 and 0.08 <= v <= 0.92)
            color = (36, 51, 67, 0 if outside else 255)
            for left, top, right, bottom, rgb in (
                (0.25, 0.25, 0.47, 0.47, (236, 243, 247)),
                (0.53, 0.25, 0.75, 0.47, (84, 196, 184)),
                (0.25, 0.53, 0.47, 0.75, (84, 196, 184)),
                (0.53, 0.53, 0.75, 0.75, (236, 243, 247)),
            ):
                if left <= u <= right and top <= v <= bottom:
                    color = rgb + (255,)
            pixels.extend(color)
    return bytes(pixels)


def png(side, transparent=False, rgb=False):
    raw = rgba(side, transparent)
    if rgb:
        rows = bytearray()
        stride = 1 + side * 4
        for y in range(side):
            rows.append(0)
            row = raw[y * stride + 1:(y + 1) * stride]
            for x in range(side):
                rows.extend(row[x * 4:x * 4 + 3])
        raw = bytes(rows)
    header = struct.pack(">IIBBBBB", side, side, 8, 2 if rgb else 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")


def ico():
    images = [png(size, transparent=True) for size in WINDOWS_SIZES]
    offset = 6 + 16 * len(images)
    directory = bytearray(struct.pack("<HHH", 0, 1, len(images)))
    for size, image in zip(WINDOWS_SIZES, images):
        directory.extend(struct.pack("<BBBBHHII", size % 256, size % 256, 0, 0, 1, 32, len(image), offset))
        offset += len(image)
    return bytes(directory) + b"".join(images)


def icns():
    entries = []
    for kind, size in ((b"icp4", 16), (b"icp5", 32), (b"icp6", 64), (b"ic07", 128),
                       (b"ic08", 256), (b"ic09", 512), (b"ic10", 1024)):
        image = png(size, transparent=True)
        entries.append(kind + struct.pack(">I", len(image) + 8) + image)
    body = b"".join(entries)
    return b"icns" + struct.pack(">I", len(body) + 8) + body


def polygon(cx, cy, radius, count=12):
    points = [(cx + radius * math.cos(2 * math.pi * n / count),
               cy + radius * math.sin(2 * math.pi * n / count)) for n in range(count)]
    return "M" + " L".join(f"{x:.2f},{y:.2f}" for x, y in points) + " Z"


HEAD = polygon(12, 8, 3, 8)
CLOCK = polygon(12, 12, 8, 12)
MIC = "M9,4 L15,4 L15,13 L9,13 Z M6,11 L6,15 L9,18 L15,18 L18,15 L18,11 M12,18 L12,21 M9,21 L15,21"
VIDEO = "M3,6 L15,6 L15,18 L3,18 Z M15,10 L21,7 L21,17 L15,14"
SLASH = " M3,3 L21,21"
ICONS = {
    "ajustes": "M3,6 L21,6 M7,3 L7,9 M3,12 L21,12 M16,9 L16,15 M3,18 L21,18 M10,15 L10,21",
    "atualizar": "M6,6 L18,6 L18,10 M15,7 L18,10 L21,7 M18,18 L6,18 L6,14 M3,17 L6,14 L9,17",
    "avancar": "M4,6 L10,12 L4,18 M11,6 L17,12 L11,18 M20,6 L20,18",
    "aviso": "M12,3 L22,20 L2,20 Z M12,8 L12,13 M12,16 L12,17",
    "bandeja": "M3,13 L3,20 L21,20 L21,13 M12,3 L12,15 M8,11 L12,15 L16,11",
    "cabo": "M5,3 L5,7 M9,3 L9,7 M3,7 L11,7 L11,12 L3,12 Z M7,12 L7,18 L17,18 L17,12 M15,6 L19,6 L19,12 L15,12 Z",
    "camera": "M3,7 L8,7 L10,4 L14,4 L16,7 L21,7 L21,20 L3,20 Z " + polygon(12, 13, 4, 8),
    "celular": "M6,3 L18,3 L18,21 L6,21 Z M10,18 L14,18",
    "check": "M4,12 L9,17 L20,6",
    "coelho": "M4,7 L10,12 L4,17 M12,7 L18,12 L12,17 M21,7 L21,17",
    "colar": "M7,5 L4,5 L4,21 L20,21 L20,5 L17,5 M8,3 L16,3 L16,7 L8,7 Z M8,11 L16,11 M8,15 L16,15",
    "copiar": "M8,8 L21,8 L21,21 L8,21 Z M16,3 L3,3 L3,16",
    "disco": CLOCK + " " + polygon(12, 12, 2, 8) + " M12,4 L12,7 M17,17 L19,19",
    "editar": "M4,16 L15,5 L19,9 L8,20 L3,21 Z M12,8 L16,12",
    "engrenagem": "M8,8 L16,8 L16,16 L8,16 Z M12,3 L12,8 M12,16 L12,21 M3,12 L8,12 M16,12 L21,12 M5,5 L8,8 M16,16 L19,19 M5,19 L8,16 M16,8 L19,5",
    "espelhar": "M3,5 L9,5 L9,19 L3,19 Z M15,5 L21,5 L21,19 L15,19 Z M12,3 L12,21",
    "espelho": "M4,5 L9,5 L9,19 L4,19 Z M15,5 L20,5 L20,19 L15,19 Z M12,3 L12,21",
    "exibir": "M3,4 L21,4 L21,17 L3,17 Z M12,17 L12,21 M8,21 L16,21",
    "fechar": "M5,5 L19,19 M19,5 L5,19",
    "gravar": polygon(12, 12, 7, 12),
    "info": "M12,4 L12,5 M10,9 L12,9 L12,20 M9,20 L15,20",
    "inicio": "M3,11 L12,3 L21,11 M5,10 L5,21 L10,21 L10,15 L14,15 L14,21 L19,21 L19,10",
    "letra_grande": "M4,20 L10,4 L16,20 M7,13 L13,13 M19,6 L19,18 M16,12 L22,12",
    "mais": "M4,12 L20,12 M12,4 L12,20",
    "menos": "M4,12 L20,12",
    "mic": MIC,
    "mic_cortado": MIC + SLASH,
    "parar": "M5,5 L19,5 L19,19 L5,19 Z",
    "pausa": "M6,4 L9,4 L9,20 L6,20 Z M15,4 L18,4 L18,20 L15,20 Z",
    "placa": "M3,6 L21,6 L21,18 L3,18 Z M6,3 L6,6 M12,3 L12,6 M18,3 L18,6 M6,10 L9,10 L9,14 L6,14 Z M14,12 L18,12",
    "play": "M7,4 L20,12 L7,20 Z",
    "recuar": "M20,6 L14,12 L20,18 M13,6 L7,12 L13,18 M4,6 L4,18",
    "relogio": CLOCK + " M12,6 L12,12 L17,15",
    "rosto": HEAD + " M4,21 L4,17 L8,14 L16,14 L20,17 L20,21",
    "sem_rede": "M4,4 L8,4 L8,8 L4,8 Z M16,16 L20,16 L20,20 L16,20 Z M8,6 L18,6 L18,16" + SLASH,
    "seta_baixo": "M5,9 L12,16 L19,9",
    "seta_direita": "M9,5 L16,12 L9,19",
    "som": "M3,9 L7,9 L12,5 L12,19 L7,15 L3,15 Z M16,8 L19,8 L19,16 L16,16 M22,6 L22,18",
    "tartaruga": "M6,7 L12,12 L6,17 M18,7 L18,17",
    "tela_cheia": "M3,9 L3,3 L9,3 M15,3 L21,3 L21,9 M21,15 L21,21 L15,21 M9,21 L3,21 L3,15",
    "texto": "M4,5 L20,5 M4,10 L20,10 M4,15 L20,15 M4,20 L13,20",
    "texto_camera": "M3,4 L12,4 M3,8 L12,8 M3,12 L9,12 M11,13 L21,13 L21,21 L11,21 Z " + polygon(16, 17, 2, 8),
    "video": VIDEO,
    "video_cortado": VIDEO + SLASH,
    "voltar": "M11,4 L3,12 L11,20 M3,12 L21,12",
    "wifi": "M2,7 L2,4 L22,4 L22,7 M6,12 L6,9 L18,9 L18,12 M10,17 L10,14 L14,14 L14,17 M12,20 L12,21",
}


def vector(path, viewport=24, side=24, stroke=True, color="#FF000000"):
    attributes = 'android:fillColor="#00000000" android:strokeColor="' + color + '" android:strokeWidth="1.7" android:strokeLineCap="round" android:strokeLineJoin="round"' if stroke else 'android:fillColor="' + color + '"'
    return XML_HEAD + XML_NOTICE + f'<vector {ANDROID_NS} android:width="{side}dp" android:height="{side}dp" android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">\n    <path {attributes} android:pathData="{path}" />\n</vector>\n'


def main():
    ios = "apps/ios/Quall/App/Assets.xcassets"
    info = {"info": {"author": "xcode", "version": 1}}
    write(ios + "/Contents.json", json.dumps(info, indent=2) + "\n")
    info["images"] = [{"filename": "AppIcon-1024.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"}]
    write(ios + "/AppIcon.appiconset/Contents.json", json.dumps(info, indent=2) + "\n")
    write(ios + "/AppIcon.appiconset/AppIcon-1024.png", png(1024, rgb=True))
    write("apps/macos/Empacotar/Quall.icns", icns())
    write("apps/windows/quall.ico", ico())
    for name, size in (("Square150x150Logo", 150), ("Square44x44Logo", 44), ("StoreLogo", 50)):
        write(f"integrations/camera-windows/msix/Assets/{name}.png", png(size, transparent=True))
    write("tools/icones/loja/play-512.png", png(512, rgb=True))
    base = "apps/android/app/src/main/res/"
    for name, path in sorted(ICONS.items()):
        write(base + f"drawable/ic_q_{name}.xml", vector(path))
    write(base + "drawable/ic_launcher_background.xml", vector("M0,0 L108,0 L108,108 L0,108 Z", viewport=108, side=108, stroke=False, color="#FF243343"))
    grid = "M29,29 L50,29 L50,50 L29,50 Z M58,29 L79,29 L79,50 L58,50 Z M29,58 L50,58 L50,79 L29,79 Z M58,58 L79,58 L79,79 L58,79 Z"
    for name in ("foreground", "monochrome"):
        write(base + f"drawable/ic_launcher_{name}.xml", vector(grid, viewport=108, side=108, stroke=False, color="#FFECF3F7"))
    write(base + "mipmap-anydpi-v26/ic_launcher.xml", XML_HEAD + XML_NOTICE + f'<adaptive-icon {ANDROID_NS}>\n    <background android:drawable="@drawable/ic_launcher_background" />\n    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n</adaptive-icon>\n')
    print(f"Generated {len(OUTPUTS)} original placeholder assets.")


if __name__ == "__main__":
    main()
